#!/usr/bin/bash

STUDIO_JDK=$HOME/Android/android-studio/jre
JRE_HOME=$STUDIO_JDK
JDK_HOME=$STUDIO_JDK
JAVA_HOME=$STUDIO_JDK
GRADLE_HOME=$HOME/Android/android-studio/gradle/gradle-3.2
PATH=$STUDIO_JDK/bin:$GRADLE_HOME/bin:$PATH

cd $HOME/Android/StudioProjects/Wifi_Mac_Change

find . -type d -iname "build" -exec rm -rf {} \;

find . -type f -iname "*.apk" -exec rm -rf {} \;

gradle clean

rm -rf .gradle
rm -rf gradle

git add -A -f
git commit -m "# clean"
git push origin master